export const apikey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnb3p4cXJ6dWhpYWt0dm1vZmFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA3NTE2NDYsImV4cCI6MjAyNjMyNzY0Nn0.P2WvLUhvIyfiVyGGuknPqtd7I7mlCeZgcB95legj7pc";
export const endpoint =
  "https://agozxqrzuhiaktvmofag.supabase.co/rest/v1/recipe";